from __future__ import annotations

from como_core.leads import LeadSearchResult

from .._params import clean_params
from ._base import AsyncResource, SyncResource

_PATH_SEARCH = "/v1/ghost/lead-search"


def _search_params(**kwargs) -> dict[str, str]:
    return clean_params(
        {
            "search": kwargs.get("search"),
            "currentCompanies": kwargs.get("current_companies"),
            "pastCompanies": kwargs.get("past_companies"),
            "locations": kwargs.get("locations"),
            "geoIds": kwargs.get("geo_ids"),
            "schools": kwargs.get("schools"),
            "currentJobTitles": kwargs.get("current_job_titles"),
            "pastJobTitles": kwargs.get("past_job_titles"),
            "firstNames": kwargs.get("first_names"),
            "lastNames": kwargs.get("last_names"),
            "industryIds": kwargs.get("industry_ids"),
            "yearsAtCurrentCompanyIds": kwargs.get("years_at_current_company_ids"),
            "yearsOfExperienceIds": kwargs.get("years_of_experience_ids"),
            "seniorityLevelIds": kwargs.get("seniority_level_ids"),
            "functionIds": kwargs.get("function_ids"),
            "recentlyChangedJobs": kwargs.get("recently_changed_jobs"),
            "postedOnLinkedin": kwargs.get("posted_on_linkedin"),
            "profileLanguages": kwargs.get("profile_languages"),
            "companyHeadcount": kwargs.get("company_headcount"),
            "companyHeadquarterLocations": kwargs.get("company_headquarter_locations"),
            "excludeLocations": kwargs.get("exclude_locations"),
            "excludeGeoIds": kwargs.get("exclude_geo_ids"),
            "excludeCurrentCompanies": kwargs.get("exclude_current_companies"),
            "excludePastCompanies": kwargs.get("exclude_past_companies"),
            "excludeSchools": kwargs.get("exclude_schools"),
            "excludeCurrentJobTitles": kwargs.get("exclude_current_job_titles"),
            "excludePastJobTitles": kwargs.get("exclude_past_job_titles"),
            "excludeIndustryIds": kwargs.get("exclude_industry_ids"),
            "excludeSeniorityLevelIds": kwargs.get("exclude_seniority_level_ids"),
            "excludeFunctionIds": kwargs.get("exclude_function_ids"),
            "excludeCompanyHeadquarterLocations": kwargs.get("exclude_company_headquarter_locations"),
            "salesNavUrl": kwargs.get("sales_nav_url"),
            "page": kwargs.get("page"),
            "sessionId": kwargs.get("session_id"),
            "usePrivatePool": kwargs.get("use_private_pool"),
            "requiredAccountId": kwargs.get("required_account_id"),
        }
    )


class LeadsResource(SyncResource):
    def search(
        self,
        *,
        search: str | None = None,
        current_companies: str | None = None,
        past_companies: str | None = None,
        locations: str | None = None,
        geo_ids: str | None = None,
        schools: str | None = None,
        current_job_titles: str | None = None,
        past_job_titles: str | None = None,
        first_names: str | None = None,
        last_names: str | None = None,
        industry_ids: str | None = None,
        years_at_current_company_ids: str | None = None,
        years_of_experience_ids: str | None = None,
        seniority_level_ids: str | None = None,
        function_ids: str | None = None,
        recently_changed_jobs: bool | None = None,
        posted_on_linkedin: bool | None = None,
        profile_languages: str | None = None,
        company_headcount: str | None = None,
        company_headquarter_locations: str | None = None,
        exclude_locations: str | None = None,
        exclude_geo_ids: str | None = None,
        exclude_current_companies: str | None = None,
        exclude_past_companies: str | None = None,
        exclude_schools: str | None = None,
        exclude_current_job_titles: str | None = None,
        exclude_past_job_titles: str | None = None,
        exclude_industry_ids: str | None = None,
        exclude_seniority_level_ids: str | None = None,
        exclude_function_ids: str | None = None,
        exclude_company_headquarter_locations: str | None = None,
        sales_nav_url: str | None = None,
        page: int | None = None,
        session_id: str | None = None,
        use_private_pool: str | None = None,
        required_account_id: str | None = None,
    ) -> LeadSearchResult:
        params = _search_params(
            search=search,
            current_companies=current_companies,
            past_companies=past_companies,
            locations=locations,
            geo_ids=geo_ids,
            schools=schools,
            current_job_titles=current_job_titles,
            past_job_titles=past_job_titles,
            first_names=first_names,
            last_names=last_names,
            industry_ids=industry_ids,
            years_at_current_company_ids=years_at_current_company_ids,
            years_of_experience_ids=years_of_experience_ids,
            seniority_level_ids=seniority_level_ids,
            function_ids=function_ids,
            recently_changed_jobs=recently_changed_jobs,
            posted_on_linkedin=posted_on_linkedin,
            profile_languages=profile_languages,
            company_headcount=company_headcount,
            company_headquarter_locations=company_headquarter_locations,
            exclude_locations=exclude_locations,
            exclude_geo_ids=exclude_geo_ids,
            exclude_current_companies=exclude_current_companies,
            exclude_past_companies=exclude_past_companies,
            exclude_schools=exclude_schools,
            exclude_current_job_titles=exclude_current_job_titles,
            exclude_past_job_titles=exclude_past_job_titles,
            exclude_industry_ids=exclude_industry_ids,
            exclude_seniority_level_ids=exclude_seniority_level_ids,
            exclude_function_ids=exclude_function_ids,
            exclude_company_headquarter_locations=exclude_company_headquarter_locations,
            sales_nav_url=sales_nav_url,
            page=page,
            session_id=session_id,
            use_private_pool=use_private_pool,
            required_account_id=required_account_id,
        )
        body = self._t.get(_PATH_SEARCH, params=params)
        return LeadSearchResult.model_validate(body)


class AsyncLeadsResource(AsyncResource):
    async def search(
        self,
        *,
        search: str | None = None,
        current_companies: str | None = None,
        past_companies: str | None = None,
        locations: str | None = None,
        geo_ids: str | None = None,
        schools: str | None = None,
        current_job_titles: str | None = None,
        past_job_titles: str | None = None,
        first_names: str | None = None,
        last_names: str | None = None,
        industry_ids: str | None = None,
        years_at_current_company_ids: str | None = None,
        years_of_experience_ids: str | None = None,
        seniority_level_ids: str | None = None,
        function_ids: str | None = None,
        recently_changed_jobs: bool | None = None,
        posted_on_linkedin: bool | None = None,
        profile_languages: str | None = None,
        company_headcount: str | None = None,
        company_headquarter_locations: str | None = None,
        exclude_locations: str | None = None,
        exclude_geo_ids: str | None = None,
        exclude_current_companies: str | None = None,
        exclude_past_companies: str | None = None,
        exclude_schools: str | None = None,
        exclude_current_job_titles: str | None = None,
        exclude_past_job_titles: str | None = None,
        exclude_industry_ids: str | None = None,
        exclude_seniority_level_ids: str | None = None,
        exclude_function_ids: str | None = None,
        exclude_company_headquarter_locations: str | None = None,
        sales_nav_url: str | None = None,
        page: int | None = None,
        session_id: str | None = None,
        use_private_pool: str | None = None,
        required_account_id: str | None = None,
    ) -> LeadSearchResult:
        params = _search_params(
            search=search,
            current_companies=current_companies,
            past_companies=past_companies,
            locations=locations,
            geo_ids=geo_ids,
            schools=schools,
            current_job_titles=current_job_titles,
            past_job_titles=past_job_titles,
            first_names=first_names,
            last_names=last_names,
            industry_ids=industry_ids,
            years_at_current_company_ids=years_at_current_company_ids,
            years_of_experience_ids=years_of_experience_ids,
            seniority_level_ids=seniority_level_ids,
            function_ids=function_ids,
            recently_changed_jobs=recently_changed_jobs,
            posted_on_linkedin=posted_on_linkedin,
            profile_languages=profile_languages,
            company_headcount=company_headcount,
            company_headquarter_locations=company_headquarter_locations,
            exclude_locations=exclude_locations,
            exclude_geo_ids=exclude_geo_ids,
            exclude_current_companies=exclude_current_companies,
            exclude_past_companies=exclude_past_companies,
            exclude_schools=exclude_schools,
            exclude_current_job_titles=exclude_current_job_titles,
            exclude_past_job_titles=exclude_past_job_titles,
            exclude_industry_ids=exclude_industry_ids,
            exclude_seniority_level_ids=exclude_seniority_level_ids,
            exclude_function_ids=exclude_function_ids,
            exclude_company_headquarter_locations=exclude_company_headquarter_locations,
            sales_nav_url=sales_nav_url,
            page=page,
            session_id=session_id,
            use_private_pool=use_private_pool,
            required_account_id=required_account_id,
        )
        body = await self._t.get(_PATH_SEARCH, params=params)
        return LeadSearchResult.model_validate(body)
